# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/Yuhcvb/Redmi10A_kernel
          kernel-dir: Yume 4.19.127 KernelSU Debug
          kernel-branch: main
          config: dandelion_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          anykernel3: true
